### ISSUE TITLE
Сделать дублирование своих сообщений, написанных с других устройств

### ISSUE THREAD

**Issue by MurzNN** [progserega/MatrixVkBot#1]
Было бы здорово видеть в Matrix свои сообщения, отправляемые с других устройств. Но т.к. это бот - то от имени юзера сообщения отправлять не получится без реализации полноценного application service, поэтому их отправлять лучше через m.notice, чтобы телефон не пилинькал.

Или, если уж делать по-настоящему, то в настройки бота можно вводить ещё данные от своего основного аккаунта, и отправлять свои сообщения через него.

**Comment by progserega** [comment]
> Или, если уж делать по-настоящему, то в настройки бота можно вводить ещё данные от своего основного аккаунта, и отправлять свои сообщения через него.

Как-то не очень "безопасно".

Первая мысль была просто убрать фильтр по "отправляемое/получаемое" и тогда все будут прилетать. Но тогда будет дилинькать на свои собственные сообщения.

> m.notice
попробую поковыряться

**Comment by progserega** [comment]
Сделал. Сообщения из других клиентов приходят в комнату как m.notice
m.notice может html, но картинки уже так не отправишь, потому html особо не поможет слать "полный фарш" через m.notice, но, наверное и не сильно нужно - главное, чтобы контекст сохранялся.

Тут проблема была - как отличить свои сообщения отправленные из матрицы и сообщения, отправленные мной же, но, из иного vk-клиента. Пока сделал так, что если текст последнего сообщения, отправленного из матрицы совпадает с моим текстом, который "прилетел" из ВК - считаем, что это дубль матрицы и не показываем notice.
Не совсем это корректно, но как иначе сделать - пока не знаю.
