### ISSUE TITLE
Убрать доступ гостям к бриджованным комнатам

### ISSUE THREAD

**Issue by MurzNN** [progserega/MatrixVkBot#10]
Заметил что при создании комнаты бот разрешает гостям в неё входить:
```
vkbot has allowed guests to join the room.
```
Наверное это лишнее, надо бы убрать?

**Comment by progserega** [comment]
Хм, странно...
Увидел это (особых настроек бот не меняет при создании комнат - только аватрку и имя).

При  том, что таки да - такой текст есть - всё же имеет место быть в настройках комнаты:
![1](https://user-images.githubusercontent.com/1297163/64168998-21408600-ce90-11e9-998d-76120060f3bc.png)

**Comment by MurzNN** [comment]
Хм, да, в свойствах комнаты у меня тоже выводится "Только приглашенные участники", странно...

**Comment by MurzNN** [comment]
Такие же действия происходят и при ручном создании прямого чата с юзером, и судя по ответам в https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$orJT0jS9UaZ4LiO0FZAKFTNAYvZIV9QigtsBP6MH75Q?via=matrix.org&via=privacytools.io&via=feneas.org это "фича" протокола, а не баг :) Закрываю.
