### ISSUE TITLE
Уведомления о создании новой комнаты сделать типом notice

### ISSUE THREAD

**Issue by MurzNN** [progserega/MatrixVkBot#11]
Сейчас при создании новой комнаты матрикс-клиент пиликает дважды: первый раз о получении приглашения в комнату, второй раз - бот пишет о том что создал комнату.  Чтобы уменьшить кол-во пиликанья предлагаю сделать сообщения о созданиях комнаты от бота форматом notice

**Comment by progserega** [comment]
добавил:
https://github.com/progserega/MatrixVkBot/commit/a01d6161e50a7ca61cccab76856370a4c34469d8
