### ISSUE TITLE
Добавить поддержку стикеров

### ISSUE THREAD

**Issue by MurzNN** [progserega/MatrixVkBot#13]
При получении сообщения со стикером из ВК - бот ругается:

> Из ВК пришёл неизвестный тип вложения (sticker) для комнаты 'Название комнаты (VK)'

Чтобы их картинкой не пересылать - можно сделать просто урлом на вк-картинку, пример https://vk.com/sticker/1-46-128

**Comment by progserega** [comment]
добавил, правда картинками - оно там то же самое, что фото, только иначе называется - чуть иной набор тегов в json.

https://github.com/progserega/MatrixVkBot/commit/a17cf9f43b87e8996bcc6d13f759a846c43c1e0f
