### ISSUE TITLE
ERROR - exception at execute start_vk_polls()

### ISSUE THREAD

**Issue by SergeyBitpix** [progserega/MatrixVkBot#22]
Бот даёт ошибку

2020-04-20 00:36:03,424 - MatrixVkBot - bot.py:2073 - start_vk_polls() ERROR - exception at execute start_vk_polls()
2020-04-20 00:36:13,435 - MatrixVkBot - bot.py:1916 - check_bot_status() DEBUG - =start function=
2020-04-20 00:36:13,435 - MatrixVkBot - bot.py:1895 - main() DEBUG - step 69
2020-04-20 00:36:13,435 - MatrixVkBot - bot.py:2027 - start_vk_polls() DEBUG - =start function=
2020-04-20 00:36:13,435 - MatrixVkBot - bot.py:2031 - start_vk_polls() DEBUG - try lock() before access global data()
2020-04-20 00:36:13,435 - MatrixVkBot - bot.py:2033 - start_vk_polls() DEBUG - success lock() before access global data
2020-04-20 00:36:13,436 - MatrixVkBot - bot.py:2072 - start_vk_polls() ERROR - Traceback (most recent call last):
  File "bot.py", line 2036, in start_vk_polls
    exit_flag=data["users"][user]["vk"]["exit"]
KeyError: 'exit'

2020-04-20 00:36:13,436 - MatrixVkBot - bot.py:2073 - start_vk_polls() ERROR - exception at execute start_vk_polls()

**Comment by SergeyBitpix** [comment]
> Бот даёт ошибку
> 
> 2020-04-20 00:36:03,424 - MatrixVkBot - bot.py:2073 - start_vk_polls() ERROR - exception at execute start_vk_polls()
> 2020-04-20 00:36:13,435 - MatrixVkBot - bot.py:1916 - check_bot_status() DEBUG - =start function=
> 2020-04-20 00:36:13,435 - MatrixVkBot - bot.py:1895 - main() DEBUG - step 69
> 2020-04-20 00:36:13,435 - MatrixVkBot - bot.py:2027 - start_vk_polls() DEBUG - =start function=
> 2020-04-20 00:36:13,435 - MatrixVkBot - bot.py:2031 - start_vk_polls() DEBUG - try lock() before access global data()
> 2020-04-20 00:36:13,435 - MatrixVkBot - bot.py:2033 - start_vk_polls() DEBUG - success lock() before access global data
> 2020-04-20 00:36:13,436 - MatrixVkBot - bot.py:2072 - start_vk_polls() ERROR - Traceback (most recent call last):
> File "bot.py", line 2036, in start_vk_polls
> exit_flag=data["users"][user]["vk"]["exit"]
> KeyError: 'exit'
> 
> 2020-04-20 00:36:13,436 - MatrixVkBot - bot.py:2073 - start_vk_polls() ERROR - exception at execute start_vk_polls()

**Comment by progserega** [comment]
починилось?

**Comment by SergeyBitpix** [comment]
Не обнаружил потока, слушающего сообщения для пользователя '
@redanarchyst:matrix.org <https://matrix.to/#/@redanarchyst:matrix.org>' и
его VK
id='85ee1955335c1548cdf7e5706c9e401d0a714c2beddcf37841e030ce12f1783f25a6da785255796cf5941'внутренняя
ошибка бота при получиении профиля пользователя в функции
update_user_info()Запускаю
процесс получения сообщений из ВК...Успешно запустил процесс получения
сообщений из ВК.Не смог получить спиоок бесед из ВК - поэтому не смог
создать новую комнату в связи с пришедшикомнату попробуйте позже :-(при
получении сообщения ВК (в функции vk_receiver_thread() ) - произошли
ошибки. Не смог принять сообщения. Обратитесь к разработчику.Изменён статус
соединения с VK на 'success', детальное описание: 'нет ошибок'Не обнаружил
потока, слушающего сообщения для пользователя '@redanarchyst:matrix.org
<https://matrix.to/#/@redanarchyst:matrix.org>' и его VK
id='85ee1955335c1548cdf7e5706c9e401d0a714c2beddcf37841e030ce12f1783f25a6da785255796cf5941'внутренняя
ошибка бота при получиении профиля пользователя в функции
update_user_info()Запускаю
процесс получения сообщений из ВК...Успешно запустил процесс получения
сообщений из ВК.redanarchyst!dialogsredanarchystvkbotНе смог получить
спиоок бесед из ВК - поэтому не смог создать новую комнату в связи с
пришедшикомнату попробуйте позже :-(при получении сообщения ВК (в функции
vk_receiver_thread() ) - произошли ошибки. Не смог принять сообщения.
Обратитесь к разработчику.Не смог получить спиоок бесед из ВК - попробуйте
позже :-(Не смог получить спиоок бесед из ВК - попробуйте позже :-(Отменил
текущий режим (listen_command) и перешёл в начальный режим ожидания команд.
Жду команд.Не обнаружил потока, слушающего сообщения для пользователя '
@redanarchyst:matrix.org <https://matrix.to/#/@redanarchyst:matrix.org>' и
его VK
id='85ee1955335c1548cdf7e5706c9e401d0a714c2beddcf37841e030ce12f1783f25a6da785255796cf5941'внутренняя
ошибка бота при получиении профиля пользователя в функции
update_user_info()Запускаю
процесс получения сообщений из ВК...Успешно запустил процесс получения
сообщений из ВК.Не смог получить спиоок бесед из ВК - поэтому не смог
создать новую комнату в связи с пришедшикомнату попробуйте позже :-(при
получении сообщения ВК (в функции vk_receiver_thread() ) - произошли
ошибки. Не смог принять сообщения. Обратитесь к разработчику.

ср, 22 апр. 2020 г. в 06:41, progserega <notifications@github.com>:
