### ISSUE TITLE
Добавить возможность игнорирования комнат при пересылке сообщений

### ISSUE THREAD

**Issue by MurzNN** [progserega/MatrixVkBot#5]
Хотелось бы иметь возможность выборочно пометить комнаты, для которых не нужно создавать комнату в Matrix и перенаправлять сообщения, что-то типа `!ignore room_id`.

**Comment by progserega** [comment]
Т.е. это делать после того, как прилетел инвейт и создалась связка ВК_диалог <-> команата_матрицы?

**Comment by MurzNN** [comment]
да, или в самой комнате писать что-то типа `!vkbot bridge_pause` (resume) или в управляющей комнате, с указанием id комнаты.

**Comment by progserega** [comment]
почему просто не "замьютить" комнату в риоте? И, соотвественно "размьютить" когда она понадобится?

**Comment by MurzNN** [comment]
Я сейчас так и делаю ;) Но некоторые комнаты совсем не хочется бриджить, чтобы не засорять Матрикс лишними сообщениями. Ну в целом не особо важная фича, без неё можно жить.

**Comment by progserega** [comment]
Т.е. опция нужна для ситуации, когда в ВК есть какая-то большая и не сильно важная группа, где много неважных сообщений и не хотелось бы, чтобы эти сообщения прилетали в матрицу без надобности, в том числе лишний раз не разряжали телефон (по идее ведь даже в "замьюченную" комнату они будут прилетать по сети - разве что только отображаться в шторке не будут). 
Ситуацию понял - можно сделать :-)

**Comment by MurzNN** [comment]
В целом да, ситуация такая как описал. С большей частью аудитории в крупных групповых чатах ВК я веду общение через ВК-клиент (изредка когда есть время), а Матрикс использую для личного общения с некоторыми людьми из ВК, плюс хочу видеть уведомления о сообщениях и от новых людей в Матриксе, чтобы ВК-шный мессенджер запускать только по требованию, когда хочется пофлеймить в групповых чатах.
В данном случае я эти комнаты мьючу, но поток из 1000+ бриджованных сообщений в день, которые я не читаю, как-то не радует ;)

**Comment by progserega** [comment]
сделал. можно тестить.
команды !pause и !resume

**Comment by MurzNN** [comment]
Супер! Только лучше префикс с названием бота добавить типа `!vkbot pause`, чтобы исключить конфликты.

**Comment by MurzNN** [comment]
Ты забыл уточнить, что их в управляющей комнате надо отправлять ;) Тогда можно и без префикса. В общем проверил, работает норм, пасиб!
