### ISSUE TITLE
Не посылать сообщения об отсутствии потока при запуске сервиса

### ISSUE THREAD

**Issue by MurzNN** [progserega/MatrixVkBot#7]
При каждом запуске сервиса бот присылает сообщения, что отсутствует поток, и он создал новый. Предлагаю посылать это только после завершения процесса инициализации. А при инициализации можно просто notice писать вида "Служба запущена (перезапущена) успешно."

**Comment by progserega** [comment]
поправил
https://github.com/progserega/MatrixVkBot/commit/c1fc2506386bcdbcd93af1d2aafde79df3cd8a17
